version: '2'
services:
  iris-api:
    container_name: iris-api
    build: 
      context: .
      dockerfile: ./Dockerfile
    restart: "on-failure"
    ports:
      - 8000:8000
  prometheus:
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command: 
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana:latest  
    restart: unless-stopped  
    ports:
      - 3000:3000  
    volumes:
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources.yaml  

